### ISSUE TITLE
NgUploaderModule is not an NgModule

### ISSUE THREAD

**Issue by uberspeck** [babarxm/ng-uploader#4]
I implemented ngUploader without any trouble and got it working. I then deleted `/node_modules` and ran `$ yarn install` again. Now I'm getting `NgUploaderModule is not an NgModule` when trying to build (via `ng serve` in cli).

- ngUploader is in my `package.json` file
- `/node_modules/ng-uploader` is present
- `NgUploaderModule` is in `imports` and `exports` of my `SharedModule`
- `SharedModule` is in `imports` of my feature module
- Finally, i'm importing `NgUploader` and `NgUploaderOptions` in my component

The error...
```
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.06 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 167 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 338 kB [initial] [rendered]

ERROR in Error: NgUploaderModule is not an NgModule
    at _getNgModuleMetadata (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/brian/dev/vault-fe/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/brian/dev/vault-fe/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/brian/dev/vault-fe/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
What am I missing?

BTW, thanks for a great module!

**Comment by babarxm** [comment]
@uberspeck which ng uploader version you are using ?

**Comment by uberspeck** [comment]
Just checked, v1.0.7 is what i have currently

**Comment by uberspeck** [comment]
I wonder if the issue I'm seeing is similar to [this one](https://github.com/vlio20/angular-datepicker/issues/8)? When I make a change to a file the build process works (like it does for [this guy](https://github.com/vlio20/angular-datepicker/issues/8#issuecomment-289031033)). However I see console errors in the browser. They fixed the issue in https://github.com/vlio20/angular-datepicker/commit/639b00d59eb1ba80668c67a976709323a4526168 but I'm not clear exactly what changes apply

**Comment by SpaceCorp-Us** [comment]
Just checked, v1.0.7 installed.
getting >>> ERROR in Error: NgUploaderModule is not an NgModule

Using >>> "@angular-mdl/core": "^4.0.8",

~ Ree

**Comment by babarxm** [comment]
@uberspeck @SpaceCorp-Us please install ng-uploader@2.0.1. Thanks
